### ISSUE TITLE
Luminosity value overwritten

### ISSUE THREAD

**Issue by MikePinball** [zesinger/ZeDMD_ESP32#1]
When changing the brightness, the luminosity "LUM" and value is overwritten. Then when changing the RGB order, only the luminosity value is updated.

**Comment by zesinger** [comment]
Yes you are right, I need to correct this

**Comment by zesinger** [comment]
I guess you mean "when changing the RGB" order?

**Comment by MikePinball** [comment]
Correct. Problem report updated.

**Comment by zesinger** [comment]
This is already corrected, I'm on the brightness scale and should upload the fixed code today
