### ISSUE TITLE
luminosity percentage

### ISSUE THREAD

**Issue by MikePinball** [zesinger/ZeDMD_ESP32#2]
Consider using a percentage rather than a value from 15 to 255 for the luminosity (say 5 to 100 in 5% increments).

Note that the luminosity curve is not a straight line and at the top end you cannot tell the difference in the last 5 values. A table might be better to give real brightness rather than just the value between 0 to 255.

**Comment by MikePinball** [comment]
This issue is not important and is only a suggestion.

**Comment by MikePinball** [comment]
See here for a discussion on non-linear LED brightness adjustment using a "S" curve. I would use a lookup table with 19 values. I might experiment with this myself and drop a pull request if it works.

**Comment by zesinger** [comment]
OK no problem, that's an easy fix anyway. There's no link in the above message.

**Comment by MikePinball** [comment]
Link added.

**Comment by zesinger** [comment]
Brightness 16 steps (using your link) coded.
