### ISSUE TITLE
[Feature Request] Clear ZeDMD Logo After Idle Timeout

### ISSUE THREAD

**Issue by megashub** [zesinger/ZeDMD_ESP32#22]
Issue created by request of maintainer. 

After a successful boot, after some time sitting idle, switch the ZeDMD logo to black. If the user interacts in any way, such as pressing the RGB or Dim buttons, the logo should display again until idle timeout duration is reached again.

This behavior would be particularly helpful in any case where displaying content on the DMD does not happen right away after booting the controller (e.g. during testing, colorization work, or mid-build of a cab).

**Comment by mkalkbrenner** [comment]
done, will be part of 3.2.1
