### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by MikePinball** [zesinger/ZeDMD_ESP32#3]
Please create a release for the latest binaries and .BAT files. Then you can point everyone to that link for the latest code.

**Comment by zesinger** [comment]
OK I'll see how to do that (I'm really noob at GitHub)

**Comment by MikePinball** [comment]
Look for "create a release" under the Releases heading on the main page. Then drag and drop your binary released file(s) which could just be a numbered ZIP file. It will automatically also take a snapshot of the source code. Add your own text description. Here is an example from Freezy: https://github.com/freezy/dmd-extensions/releases

**Comment by zesinger** [comment]
Thanks for the help.

**Comment by zesinger** [comment]
Done here https://github.com/zesinger/ZeDMD_ESP32/releases/tag/ZeDMD
